# Generated by Django 5.1.7 on 2025-03-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('running_time', models.IntegerField()),
                ('image_url', models.URLField()),
                ('imdb_url', models.URLField()),
            ],
        ),
    ]
