# Generated by Django 5.1.7 on 2025-03-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movixapp', '0002_movie_imdb_rating_movie_language_movie_plot_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot_summary',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CastAndCrew',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
