# Generated by Django 5.1.5 on 2025-03-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movixapp', '0004_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
